apiVersion: apps/v1
kind: Deployment
metadata:
  name: "novo-exemplo-palm-pay"
  labels:
    app: "novo-exemplo-palm-pay"
spec:
  selector:
    matchLabels:
      app: "novo-exemplo-palm-pay"
  replicas: 1
  template:
    metadata:
      labels:
        app: "novo-exemplo-palm-pay"
    spec:
      containers:
        - name: "novo-exemplo-palm-pay"
          image: registry.localhost:5000/novo-exemplo-palm-pay:v0.01
          imagePullPolicy: Always

          ports:
          - containerPort: 8181
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi

